let itemList = [
  //Planks
  ["Spruce Planks", 4, "Spruce Logs", 1],
  ["Oak Planks", 4, "Oak Logs", 1],
  ["Dark Oak Planks", 4, "Dark Oak Logs", 1],
  ["Cherry Planks", 4, "Cherry Logs", 1],
  ["Birch Planks", 4, "Birch Logs", 1],
  ["Acacia Planks", 4, "Acacia Logs", 1],
  ["Mangrove Planks", 4, "Mangrove Logs", 1],
  ["Jungle Planks", 4, "Jungle Logs", 1],
  ["Crimson Planks", 4, "Crimson Logs", 1],
  ["Warped Planks", 4, "Warped Logs", 1],
  ["Bamboo Planks", 2, "Blocks of Bamboo", 1],


 //Other building materials
  ["Bricks", 1, "Brick", 4], 
  ["Painting", 1, "Wool", 1, "Sticks", 8], 
  

  //Beds
  ["Blue Bed", 1, "Blue Wool", 3, "Planks", 3], 
  ["Light Blue Bed", 1, "Light Blue Wool", 3, "Planks", 3], 
  ["Purple Bed", 1, "Purple Wool", 3, "Planks", 3], 
  ["Red Bed", 1, "Red Wool", 3, "Planks", 3], 
  ["Magenta Bed", 1, "Magenta Wool", 3, "Planks", 3], 
  ["Orange Bed", 1, "Orange Wool", 3, "Planks", 3], 
  ["Yellow Bed", 1, "Yellow Wool", 3, "Planks", 3], 
  ["Green Bed", 1, "Green Wool", 3, "Planks", 3], 
  ["Lime Bed", 1, "Lime Wool", 3, "Planks", 3], 
  ["Black Bed", 1, "Black Wool", 3, "Planks", 3], 
  ["White Bed", 1, "White Wool", 3, "Planks", 3], 
  ["Gray Bed", 1, "Gray Wool", 3, "Planks", 3], 
  ["Cyan Bed", 1, "Cyan Wool", 3, "Planks", 3],
  ["Pink Bed", 1, "Pink Wool", 3, "Planks", 3],
  

  //Slabs
  ["Spruce Slab", 6, "Spruce Planks", 3],  
  ["Oak Slab", 6, "Oak Planks", 3],
  ["Dark Oak Slab", 6, "Dark Oak Planks", 3],
  ["Cherry Slab", 6, "Cherry Planks", 3],
  ["Birch Slab", 6, "Birch Planks", 3],
  ["Acacia Slab", 6, "Acacia Planks", 3],
  ["Mangrove Slab", 6, "Mangrove Planks", 3],
  ["Jungle Slab", 6, "Jungle Planks", 3],
  ["Crimson Slab", 6, "Crimson Planks", 3],
  ["Warped Slab", 6, "Warped Planks", 3],
  ["Bamboo Slab", 6, "Bamboo Planks", 3],
  ["Bamboo Mosaic Slab", 6, "Bamboo Mosaic", 3],
  ["Cobblestone Slab", 6, "Cobblestone", 3],
  ["Stone Slab", 6, "Stone", 3],
  ["Stone Brick Slab", 6, "Stone Bricks", 3],
  ["Sandstone Slab", 6, "Sandstone", 3],
  ["Smooth Sandstone Slab", 6, "Smooth Sandstone", 3],
  ["Cut Sandstone Slab", 6, "Cut Sandstone", 3],
  ["Red Sandstone Slab", 6, "Red Sandstone", 3],
  ["Brick Slab", 6, "Bricks", 3],
  ["Deepslate Brick Slab", 6, "Deepslate Bricks", 3],
  ["Deepslate Tile Slab", 6, "Deepslate Tiles", 3],
  ["Mossy Cobblestone Slab", 6, "Mossy Cobblestone", 3],
  ["Mossy Stone Brick Slab", 6, "Mossy Stone Brick", 3],
  ["Smooth Stone Slab", 6, "Smooth Stone", 3],
  ["Mud Brick Slab", 6, "Mud Brick", 3],
  ["Purpur Slab", 6, "Purpur", 3],
  ["Blackstone Slab", 6, "Blackstone", 3],
  ["Polished Blackstone Slab", 6, "Polished Blackstone", 3],
  ["Polished Blackstone Brick Slab", 6, "Polished Blackstone Brick", 3],
  ["Granite Slab", 6, "Granite", 3],
  ["Polished Granite Slab", 6, "Polished Granite", 3],
  ["Andesite Slab", 6, "Andesite", 3],
  ["Polished Andesite Slab", 6, "Polished Andesite", 3],
  ["Diorite Slab", 6, "Diorite", 3],
  ["Polished Diorite Slab", 6, "Polished Diorite", 3],
  ["Prismarine Slab", 6, "Prismarine", 3],
  ["Prismarine Brick Slab", 6, "Prismarine Brick", 3],
  ["Dark Prismarine Slab", 6, "Dark Prismarine", 3],
  ["Nether Brick Slab", 6, "Nether Brick", 3],
  ["Red Nether Brick Slab", 6, "Red Nether Brick", 3],
  ["End Stone Brick Slab", 6, "End Stone Brick", 3],
  ["Quartz Slab", 6, "Quartz", 3],
  ["Smooth Quartz Slab", 6, "Smooth Quartz", 3],
  ["Cut Copper Slab", 6, "Cut Copper", 3],
  ["Exposed Cut Copper Slab", 6, "Exposed Cut Copper", 3],
  ["Weathered Cut Copper Slab", 6, "Weathered Cut Copper", 3],
  ["Oxidized Cut Copper Slab", 6, "Oxidized Cut Copper", 3],
  ["Waxed Cut Copper Slab", 6, "Waxed Cut Copper", 3],
  ["Waxed Exposed Cut Copper Slab", 6, "Waxed Exposed Cut Copper", 3],
  ["Waxed Weathered Cut Copper Slab", 6, "Waxed Weathered Cut Copper", 3],
  ["Waxed Oxidized Cut Copper Slab", 6, "Waxed Oxidized Cut Copper", 3],

  //Doors
  ["Acacia Door", 3, "Acacia Planks", 6], 
  ["Birch Door", 3, "Birch Planks", 6], 
  ["Cherry Door", 3, "Cherry Planks", 6], 
  ["Oak Door", 3, "Oak Planks", 6],
  ["Dark Oak Door", 3, "Dark Oak Planks", 6],
  ["Spruce Door", 3, "Spruce Planks", 6],
  ["Mangrove Door", 3, "Mangrove Planks", 6],
  ["Jungle Door", 3, "Jungle Planks", 6],
  ["Bamboo Door", 3, "Bamboo Planks", 6],
  ["Crimson Door", 3, "Crimson Planks", 6],
  ["Warped Door", 3, "Warped Planks", 6],


   //Stairs
   ["Acacia Stairs", 4, "Acacia Planks", 6], 
   ["Birch Stairs", 4, "Birch Planks", 6], 
   ["Cherry Stairs", 4, "Cherry Planks", 6], 
   ["Oak Stairs", 4, "Oak Planks", 6],
   ["Dark Oak Stairs", 4, "Dark Oak Planks", 6],
   ["Spruce Stairs", 4, "Spruce Planks", 6],
   ["Mangrove Stairs", 4, "Mangrove Planks", 6],
   ["Jungle Stairs", 4, "Jungle Planks", 6],
   ["Bamboo Stairs", 4, "Bamboo Planks", 6],
   ["Bamboo Mosaic Stairs", 4, "Bamboo Mosaic", 6], 
   ["Crimson Stairs", 4, "Crimson Planks", 6],
   ["Warped Stairs", 4, "Warped Planks", 6],

   ["Andesite Stairs", 4, "Andesite", 6], 
   ["Cobblestone Stairs", 4, "Cobblestone", 6], 
   ["Blackstone Stairs", 4, "Blackstone", 6],
   ["Brick Stairs", 4, "Bricks", 6],
   ["Cobbled Deepslate Stairs", 4, "Cobbled Deepslate", 6],
   ["Cut Copper Stairs", 4, "Cut Copper", 6],
   ["Dark Prismarine Stairs", 4, "Dark Prismarine", 6],
   ["Diorite Stairs", 4, "Diorite", 6],
   ["Deepslate Brick Stairs", 4, "Deepslate Brick", 6],
   ["Deepslate Tile Stairs", 4, "Deepslate Tile", 6],
   ["End Stone Brick Stairs", 4, "End Stone Brick", 6],
   ["Exposed Cut Copper Stairs", 4, "Exposed Cut Copper", 6],
   ["Mossy Cobblestone Stairs", 4, "Mossy Cobblestone", 6],
   ["Mossy Stone Brick Stairs", 4, "Mossy Stone Brick", 6],
   ["Mud Brick Stairs", 4, "Mud Brick", 6],
   ["Nether Brick Stairs", 4, "Nether Brick", 6],
   ["Oxidized Cut Copper Stairs", 4, "Oxidized Cut Copper", 6],
   ["Polished Andesite Stairs", 4, "Polished Andesite", 6],
   ["Polished Blackstone Stairs", 4, "Polished Blackstone", 6],
   ["Polished Blackstone Brick Stairs", 4, "Polished Blackstone Brick", 6],
   ["Polished Deepslate Stairs", 4, "Polished Deepslate", 6],
   ["Polished Diorite Stairs", 4, "Polished Deepslate", 6],
   ["Prismarine Brick Stairs", 4, "Prismarine Brick", 6],
   ["Purpur Stairs", 4, "Purpur Brick", 6],
   ["Quartz Stairs", 4, "Quartz", 6],
   ["Red Nether Brick Stairs", 4, "Red Nether Brick", 6],
   ["Red Sandstone Stairs", 4, "Red Sandstone", 6],
   ["Sandstone Stairs", 4, "Sandstone", 6],
   ["Smooth Quartz Stairs", 4, "Smooth Quartz", 6],
   ["Smooth Red Sandstone Stairs", 4, "Smooth Red Sandstone", 6],
   ["Smooth Sandstone Stairs", 4, "Smooth Sandstone", 6],
   ["Stone Brick Stairs", 4, "Stone Brick", 6],
   ["Stone Stairs", 4, "Stone", 6],
   ["Waxed Cut Copper Stairs", 4, "Waxed Cut Copper", 6],
   ["Waxed Oxidized Cut Copper Stairs", 4, "Waxed Oxidized Cut Copper", 6],
   ["Waxed Weathered Cut Copper Stairs", 4, "Waxed Weathered Cut Copper", 6],
   ["Weathered Cut Copper Stairs", 4, "Weathered Cut Copper", 6],

   //Walls
   ["Andesite Wall", 6, "Andesite", 6], 
   ["Cobblestone Wall", 6, "Cobblestone", 6], 
   ["Blackstone Wall", 6, "Blackstone", 6], 
   ["Cobbled Deepslate Wall", 6, "Cobbled Deepslate", 6], 
   ["Deepslate Brick Wall", 6, "Deepslate Brick", 6], 
   ["Deepslate Tile Wall", 6, "Deepslate Tile", 6], 
   ["Diorite Wall", 6, "Diorite", 6], 
   ["Mossy Cobblestone Wall", 6, "Mossy Cobblestone", 6], 
   ["Mossy Stone Brick Wall", 6, "Mossy Stone Brick", 6], 
   ["Mud Brick Wall", 6, "Mud Brick", 6], 
   ["Nether Brick Wall", 6, "Nether Brick", 6], 
   ["Polished Blackstone Brick Wall", 6, "Polished Blackstone Brick", 6], 
   ["Polished Blackstone Wall", 6, "Polished Blackstone", 6], 
   ["Polished Deepslate Wall", 6, "Polished Deepslate ", 6], 
   ["Prismarine Wall", 6, "Prismarine", 6], 
   ["Sandstone Wall", 6, "Sandstone", 6],
   ["Red Sandstone Wall", 6, "Red Sandstone", 6],
   ["Red Nether Brick Wall", 6, "Red Nether Brick", 6],
   ["Stone Brick Wall", 6, "Stone Brick", 6], 




  //Gates

  ["Acacia Gate", 1, "Acacia Planks", 2, "Sticks", 4],
  ["Birch Gate", 1, "Birch Planks", 2, "Sticks", 4],
  ["Cherry Gate", 1, "Cherry Planks", 2, "Sticks", 4],
  ["Oak Gate", 1, "Oak Planks", 2, "Sticks", 4],
  ["Dark Oak Gate", 1, "Oak Planks", 2, "Sticks", 4],
  ["Spruce Gate", 1, "Spruce Planks", 2, "Sticks", 4],
  ["Jungle Gate", 1, "Jungle Planks", 2, "Sticks", 4],
  ["Mangrove Gate", 1, "Mangrove Planks", 2, "Sticks", 4],
  ["Bamboo Gate", 1, "Bamboo Planks", 2, "Sticks", 4],
  ["Crimson Gate", 1, "Crimson Planks", 2, "Sticks", 4],
  ["Warped Gate", 1, "Warped Planks", 2, "Sticks", 4],
  //Fences
  ["Acacia Fence", 3, "Acacia Planks", 4, "Sticks", 2], 
  ["Birch Fence", 3, "Birch Planks", 4, "Sticks", 2], 
  ["Oak Fence", 3, "Oak Planks", 4, "Sticks", 2], 
  ["Cherry Fence", 3, "Oak Planks", 4, "Sticks", 2], 
  ["Dark Oak Fence", 3, "Dark Oak Planks", 4, "Sticks", 2], 
  ["Spruce Fence", 3, "Spruce Planks", 4, "Sticks", 2], 
  ["Jungle Fence", 3, "Jungle Planks", 4, "Sticks", 2], 
  ["Mangrove Fence", 3, "Mangrove Planks", 4, "Sticks", 2], 
  ["Crimson Fence", 3, "Crimson Planks", 4, "Sticks", 2], 
  ["Warped Fence", 3, "Warped Planks", 4, "Sticks", 2], 
  ["Bamboo Fence", 3, "Bamboo Planks", 4, "Sticks", 2], 
  //hanging signs
  ["Acacia Hanging Sign", 6, "Iron Chains", 2, "Stripped Acacia Logs", 6], 
  ["Birch Hanging Sign", 6, "Iron Chains", 2, "Stripped Birch Logs", 6], 
  ["Oak Hanging Sign", 6, "Iron Chains", 2, "Stripped Oak Logs", 6], 
  ["Cherry Hanging Sign", 6, "Iron Chains", 2, "Stripped Cherry Logs", 6], 
  ["Dark Oak Hanging Sign", 6, "Iron Chains", 2, "Stripped Dark Oak Logs", 6], 
  ["Spruce Hanging Sign", 6, "Iron Chains", 2, "Stripped Spruce Logs", 6], 
  ["Jungle Hanging Sign", 6, "Iron Chains", 2, "Stripped Jungle Logs", 6], 
  ["Mangrove Hanging Sign", 6, "Iron Chains", 2, "Stripped Mangrove Logs", 6], 
  ["Crimson Hanging Sign", 6, "Iron Chains", 2, "Stripped Crimson Logs", 6], 
  ["Warped Hanging Sign", 6, "Iron Chains", 2, "Stripped Warped Logs", 6], 
  ["Bamboo Hanging Sign", 6, "Iron Chains", 2, "Stripped Bamboo", 6], 

//Add other fences and signs


["Birch Sign", 3, "Birch Planks", 6, "Sticks", 1], 
["Acacia Sign", 3, "Acacia Planks", 6, "Sticks", 1],
["Oak Sign", 3, "Oak Planks", 6, "Sticks", 1],
["Dark Oak Sign", 3, "Dark Oak Planks", 6, "Sticks", 1],
["Jungle Sign", 3, "Jungle Planks", 6, "Sticks", 1],
["Spruce Sign", 3, "Jungle Planks", 6, "Sticks", 1],
["Cherry Sign", 3, "Cherry Planks", 6, "Sticks", 1],
["Mangrove Sign", 3, "Mangrove Planks", 6, "Sticks", 1],
["Bamboo Sign", 3, "Bamboo Planks", 6, "Sticks", 1],
["Crimson Sign", 3, "Crimson Planks", 6, "Sticks", 1],
["Warped Sign", 3, "Warped Planks", 6, "Sticks", 1],

//All the signs are done

  //Redstone Items
  ["Observer", 1, "Cobblestone", 6, "Redstone Dust", 2, "Nether Quartz", 1],
  ["Acacia Button", 1, "Acacia Planks", 1],




  //Food Items
  ["Hay Block", 1, "Wheat", 9],
  ["Cake", 1, "Wheat", 3, "Milk Bucket", 3, "Sugar", 2, "Eggs", 1],


  //Tools
  ["Wooden Axe", 1, "Planks", 3, "Sticks", 2],
  ["Wooden Sword", 1, "Planks", 2, "Sticks", 1],
  ["Wooden Pickaxe", 1, "Planks", 3, "Sticks", 2],
  ["Wooden Shovel", 1, "Planks", 1, "Sticks", 2],
  ["Wooden Hoe", 1, "Planks", 2, "Sticks", 2],
  ["Stone Axe", 1, "Cobblestone", 3, "Sticks", 2],
  ["Stone Sword", 1, "Cobblestone", 2, "Sticks", 1],
  ["Stone Pickaxe", 1, "Cobblestone", 3, "Sticks", 2],
  ["Stone Shovel", 1, "Cobblestone", 1, "Sticks", 2],
  ["Stone Hoe", 1, "Cobblestone", 2, "Sticks", 2],
  ["Iron Axe", 1, "Iron Ingots", 3, "Sticks", 2],
  ["Iron Sword", 1, "Iron Ingots", 2, "Sticks", 1],
  ["Iron Pickaxe", 1, "Iron Ingots", 3, "Sticks", 2],
  ["Iron Shovel", 1, "Iron Ingots", 1, "Sticks", 2],
  ["Iron Hoe", 1, "Gold Ingots", 2, "Sticks", 2],
  ["Golden Axe", 1, "Gold Ingots", 3, "Sticks", 2],
  ["Golden Sword", 1, "Gold Ingots", 2, "Sticks", 1],
  ["Golden Pickaxe", 1, "Gold Ingots", 3, "Sticks", 2],
  ["Golden Shovel", 1, "Gold Ingots", 1, "Sticks", 2],
  ["Golden Hoe", 1, "Gold Ingots", 2, "Sticks", 2],
  ["Diamond Axe", 1, "Diamond Ingots", 3, "Sticks", 2],
  ["Diamond Sword", 1, "Diamond Ingots", 2, "Sticks", 1],
  ["Diamond Pickaxe", 1, "Diamond Ingots", 3, "Sticks", 2],
  ["Diamond Shovel", 1, "Diamond Ingots", 1, "Sticks", 2],
  ["Diamond Hoe", 1, "Diamond Ingots", 2, "Sticks", 2],
  ["Netherite Axe", 1, "Netherite Ingots", 3, "Sticks", 2],
  ["Netherite Sword", 1, "Netherite Ingots", 2, "Sticks", 1],
  ["Netherite Pickaxe", 1, "Netherite Ingots", 3, "Sticks", 2],
  ["Netherite Shovel", 1, "Netherite Ingots", 1, "Sticks", 2],
  ["Netherite Hoe", 1, "Netherite Ingots", 2, "Sticks", 2],
  ["Torch", 4, "Coal", 1, "Sticks", 1],
  ["Chest", 1, "Planks", 8],
  ["Acacia Boat", 1, "Acacia Planks", 5],
  ["Birch Boat", 1, "Birch Planks", 5],
  ["Spruce Boat", 1, "Spruce Planks", 5],
  ["Oak Boat", 1, "Oak Planks", 5],
  ["Dark Oak Boat", 1, "Dark Oak Planks", 5],
  ["Cherry Boat", 1, "Cherry Planks", 5],
  ["Jungle Boat", 1, "Jungle Planks", 5],
  ["Mangrove Boat", 1, "Mangrove Planks", 5],
  ["Bamboo Raft", 1, "Bamboo Planks", 5],
  ["Stick", 4, "Planks", 2], 
  ["Crafting Table", 1, "Planks", 4],
  ["Boat with Chest", 1, "Chest", 1, "Boat", 1],
  ["Furnace", 1, "Cobblestone", 8],
  ["Ladder", 3, "Sticks", 7] 
  




  //Stone Items
    
   
   
    
    
  ];
