let itemList = [
  //Planks
  ["Spruce Planks", 4, "Spruce Logs", 1],
  ["Oak Planks", 4, "Oak Logs", 1],
  ["Dark Oak Planks", 4, "Dark Oak Logs", 1],
  ["Cherry Planks", 4, "Cherry Logs", 1],
  ["Birch Planks", 4, "Birch Logs", 1],
  ["Acacia Planks", 4, "Acacia Logs", 1],
  ["Mangrove Planks", 4, "Mangrove Logs", 1],
  ["Jungle Planks", 4, "Jungle Logs", 1],
  ["Crimson Planks", 4, "Crimson Logs", 1],
  ["Warped Planks", 4, "Warped Logs", 1],
  ["Bamboo Planks", 2, "Blocks of Bamboo", 1],
  //Other building materials
  ["Bricks", 1, "Brick", 4],
  ["Painting", 1, "Wool", 1, "Sticks", 8],
  ["Paper", 3, "Sugarcane", 3],
  ["Book", 1, "Paper", 3, "Leather", 1],
  ["Bookshelf", 1, "Books", 3, "Planks", 6],
  ["Scaffolding", 6, "String", 1, "Bamboo", 6],
  ["Barrel", 1, "Planks", 6, "Slabs", 2],
  ["Enchanting Table", 1, "Obsidian", 3, "Diamonds", 2, "Books", 1],
  ["Anvil", 1, "Iron Ingots", 4, "Iron Blocks", 3],
  ["Ender Chest", 1, "Obsidian", 8, "Eye of Ender", 1],
  ["Iron Bars", 16, "Iron Ingots", 6],
  ["Item Frame", 1, "Sticks", 8, "Leather", 1],
  ["Armor Stand", 1, "Sticks", 6, "Stone Slab", 1],
  ["Soul Torch", 4, "Coal", 1, "Sticks", 1, "Soul Sand", 1],
  ["Lantern", 1, "Iron Nuggets", 8, "Torch", 1],
  ["Soul Lantern", 1, "Iron Nuggets", 8, "Soul Torch", 1],
  ["Campfire", 1, "Coal", 1, "Stick", 3, "Logs", 3],
  ["Soul Campfire", 1, "Soul Sand", 1, "Sticks", 3, "Logs", 3],
  ["Lead", 2, "String", 4, "Slime Ball", 1],
  ["Chain", 1, "Iron Ingot", 1, "Iron Nugget", 2],
  //Workstations
  ["Blast Furnace", 1, "Iron Ingot", 5, "Smooth Stone", 3, "Furnace", 1],
  ["Smoker", 1, "Furnace", 1, "Logs", 4],
  ["Cartography Table", 1, "Paper", 2, "Planks", 4],
  ["Composter", 1, "Slabs", 7],
  ["Fletching Table", 1, "Flint", 2, "Planks", 4],
  ["Smithing Table", 1, "Iron Ingot", 2, "Planks", 4],
  ["Stonecutter", 1, "Iron Ingot", 1, "Stone", 3],  
  ["Grindstone", 1, "Sticks", 2, "Planks", 2, "Stone Slab", 1],
  ["Lectern", 1, "Bookcase", 1, "Wooden Slab", 4],
  ["Loom", 1, "String", 2, "Planks", 2],
  ["Beehive", 1, "Honeycomb", 3, "Planks", 6],
  //Stained Glass
  ["White Stained Glass", 8, "Glass", 8, "White Dye", 1],
  ["Blue Stained Glass", 8, "Glass", 8, "Blue Dye", 1],
  ["Light Blue Stained Glass", 8, "Glass", 8, "Light Blue Dye", 1],
  ["Red Stained Glass", 8, "Glass", 8, "Red Dye", 1],
  ["Pink Stained Glass", 8, "Glass", 8, "Pink Dye", 1],
  ["Purple Stained Glass", 8, "Glass", 8, "Purple Dye", 1],
  ["Orange Stained Glass", 8, "Glass", 8, "Orange Dye", 1],
  ["Yellow Stained Glass", 8, "Glass", 8, "Yellow Dye", 1],
  ["Lime Stained Glass", 8, "Glass", 8, "Lime Dye", 1],
  ["Magenta Stained Glass", 8, "Glass", 8, "Magenta Dye", 1],
  ["Cyan Stained Glass", 8, "Glass", 8, "Cyan Dye", 1],
  ["Black Stained Glass", 8, "Glass", 8, "Black Dye", 1],
  ["Gray Stained Glass", 8, "Glass", 8, "Gray Dye", 1],
  ["Brown Stained Glass", 8, "Glass", 8, "Brown Dye", 1],
  ["Light Gray Stained Glass", 8, "Glass", 8, "Light Gray Dye", 1],
  //Glass Panes
  ["White Stained Glass Pane", 16, "White Stained Glass", 6],
  ["Blue Stained Glass Pane", 16, "Blue Stained Glass", 6],
  ["Light Blue Stained Glass Pane", 16, "Light Blue Stained Glass", 6],
  ["Red Stained Glass Pane", 16, "Red Stained Glass", 6],
  ["Pink Stained Glass Pane", 16, "Pink Stained Glass", 6],
  ["Purple Stained Glass Pane", 16, "Purple Stained Glass", 6],
  ["Orange Stained Glass Pane", 16, "Orange Stained Glass", 6],
  ["Yellow Stained Glass Pane", 16, "Yellow Stained Glass", 6],
  ["Lime Stained Glass Pane", 16, "Lime Stained Glass", 6],
  ["Magenta Stained Glass Pane", 16, "Magenta Stained Glass", 6],
  ["Cyan Stained Glass Pane", 16, "Cyan Stained Glass", 6],
  ["Black Stained Glass Pane", 16, "Black Stained Glass", 6],
  ["Gray Stained Glass Pane", 16, "Gray Stained Glass", 6],
  ["Brown Stained Glass Pane", 16, "Brown Stained Glass", 6],
  ["Light Gray Stained Glass Pane", 16, "Light Gray Stained Glass", 6],
  //Banners
  ["White Banner", 1, "White Wool", 6],
  ["Blue Banner", 1, "Blue Wool", 6],
  ["Cyan Banner", 1, "Cyan Wool", 6],
  ["Light Blue Banner", 1, "Light Blue Wool", 6],
  ["Red Banner", 1, "Red Wool", 6],
  ["Pink Banner", 1, "Pink Wool", 6],
  ["Purple Banner", 1, "Purple Wool", 6],
  ["Orange Banner", 1, "Orange Wool", 6],
  ["Yellow Banner", 1, "Yellow Wool", 6],
  ["Lime Banner", 1, "Lime Wool", 6],
  ["Green Banner", 1, "Green Wool", 6],
  ["Magenta Banner", 1, "Magenta Wool", 6],
  ["Light Gray Banner", 1, "Gray Wool", 6],
  ["Gray Banner", 1, "Gray Wool", 6],
  ["Black Banner", 1, "Black Wool", 6],
  ["Brown Banner", 1, "Brown Wool", 6],
  //Beds
  ["Blue Bed", 1, "Blue Wool", 3, "Planks", 3],
  ["Light Blue Bed", 1, "Light Blue Wool", 3, "Planks", 3],
  ["Purple Bed", 1, "Purple Wool", 3, "Planks", 3],
  ["Red Bed", 1, "Red Wool", 3, "Planks", 3],
  ["Magenta Bed", 1, "Magenta Wool", 3, "Planks", 3],
  ["Orange Bed", 1, "Orange Wool", 3, "Planks", 3],
  ["Yellow Bed", 1, "Yellow Wool", 3, "Planks", 3],
  ["Green Bed", 1, "Green Wool", 3, "Planks", 3],
  ["Lime Bed", 1, "Lime Wool", 3, "Planks", 3],
  ["Black Bed", 1, "Black Wool", 3, "Planks", 3],
  ["Brown Bed", 1, "Brown Wool", 3, "Planks", 3],
  ["White Bed", 1, "White Wool", 3, "Planks", 3],
  ["Light Gray Bed", 1, "Gray Wool", 3, "Planks", 3],
  ["Gray Bed", 1, "Gray Wool", 3, "Planks", 3],
  ["Cyan Bed", 1, "Cyan Wool", 3, "Planks", 3],
  ["Pink Bed", 1, "Pink Wool", 3, "Planks", 3],
  //Ocean Biome
  ["Dark Prismarine", 1, "Prismarine Shards", 8, "Ink Sac", 1],
  ["Prismarine", 1, "Prismarine Shards", 4],
  ["Prismarine Bricks", 1, "Prismarine Shards", 9],
  ["Sea Lantern", 1, "Prismarine Shards", 4, "Prismarine Crystals", 5],
  ["Mossy Cobblestone", 1, "Cobblestone", 1, "Moss Block", 1],
  //Slabs
  ["Spruce Slab", 6, "Spruce Planks", 3],
  ["Oak Slab", 6, "Oak Planks", 3],
  ["Dark Oak Slab", 6, "Dark Oak Planks", 3],
  ["Cherry Slab", 6, "Cherry Planks", 3],
  ["Birch Slab", 6, "Birch Planks", 3],
  ["Acacia Slab", 6, "Acacia Planks", 3],
  ["Mangrove Slab", 6, "Mangrove Planks", 3],
  ["Jungle Slab", 6, "Jungle Planks", 3],
  ["Crimson Slab", 6, "Crimson Planks", 3],
  ["Warped Slab", 6, "Warped Planks", 3],
  ["Bamboo Slab", 6, "Bamboo Planks", 3],
  ["Bamboo Mosaic Slab", 6, "Bamboo Mosaic", 3],
  ["Cobblestone Slab", 6, "Cobblestone", 3],
  ["Stone Slab", 6, "Stone", 3],
  ["Stone Brick Slab", 6, "Stone Bricks", 3],
  ["Red Sandstone", 1, "Red Sand", 4],
  ["Sandstone Slab", 6, "Sandstone", 3],
  ["Smooth Sandstone Slab", 6, "Smooth Sandstone", 3],
  ["Cut Sandstone Slab", 6, "Cut Sandstone", 3],
  ["Red Sandstone Slab", 6, "Red Sandstone", 3],
  ["Brick Slab", 6, "Bricks", 3],
  ["Deepslate Brick Slab", 6, "Deepslate Bricks", 3],
  ["Deepslate Tile Slab", 6, "Deepslate Tiles", 3],
  ["Mossy Cobblestone Slab", 6, "Mossy Cobblestone", 3],
  ["Mossy Stone Brick Slab", 6, "Mossy Stone Brick", 3],
  ["Smooth Stone Slab", 6, "Smooth Stone", 3],
  ["Mud Brick Slab", 6, "Mud Brick", 3],
  ["Purpur Slab", 6, "Purpur", 3],
  ["Blackstone Slab", 6, "Blackstone", 3],
  ["Polished Blackstone Slab", 6, "Polished Blackstone", 3],
  ["Polished Blackstone Brick Slab", 6, "Polished Blackstone Brick", 3],
  ["Granite Slab", 6, "Granite", 3],
  ["Polished Granite Slab", 6, "Polished Granite", 3],
  ["Andesite Slab", 6, "Andesite", 3],
  ["Polished Andesite Slab", 6, "Polished Andesite", 3],
  ["Diorite Slab", 6, "Diorite", 3],
  ["Polished Diorite Slab", 6, "Polished Diorite", 3],
  ["Prismarine Slab", 6, "Prismarine", 3],
  ["Prismarine Brick Slab", 6, "Prismarine Brick", 3],
  ["Dark Prismarine Slab", 6, "Dark Prismarine", 3],
  ["Nether Brick Slab", 6, "Nether Brick", 3],
  ["Red Nether Brick Slab", 6, "Red Nether Brick", 3],
  ["End Stone Brick Slab", 6, "End Stone Brick", 3],
  ["Quartz Slab", 6, "Quartz", 3],
  ["Smooth Quartz Slab", 6, "Smooth Quartz", 3],
  ["Cut Copper Slab", 6, "Cut Copper", 3],
  ["Exposed Cut Copper Slab", 6, "Exposed Cut Copper", 3],
  ["Weathered Cut Copper Slab", 6, "Weathered Cut Copper", 3],
  ["Oxidized Cut Copper Slab", 6, "Oxidized Cut Copper", 3],
  ["Waxed Cut Copper Slab", 6, "Waxed Cut Copper", 3],
  ["Waxed Exposed Cut Copper Slab", 6, "Waxed Exposed Cut Copper", 3],
  ["Waxed Weathered Cut Copper Slab", 6, "Waxed Weathered Cut Copper", 3],
  ["Waxed Oxidized Cut Copper Slab", 6, "Waxed Oxidized Cut Copper", 3],
  //Doors
  ["Acacia Door", 3, "Acacia Planks", 6],
  ["Birch Door", 3, "Birch Planks", 6],
  ["Cherry Door", 3, "Cherry Planks", 6],
  ["Oak Door", 3, "Oak Planks", 6],
  ["Dark Oak Door", 3, "Dark Oak Planks", 6],
  ["Spruce Door", 3, "Spruce Planks", 6],
  ["Mangrove Door", 3, "Mangrove Planks", 6],
  ["Jungle Door", 3, "Jungle Planks", 6],
  ["Bamboo Door", 3, "Bamboo Planks", 6],
  ["Crimson Door", 3, "Crimson Planks", 6],
  ["Warped Door", 3, "Warped Planks", 6],
  //Trap Doors
  ["Acacia Trapdoor", 3, "Acacia Planks", 6],
  ["Birch Trapdoor", 3, "Birch Planks", 6],
  ["Cherry Trapdoor", 3, "Cherry Planks", 6],
  ["Oak Trapdoor", 3, "Oak Planks", 6],
  ["Dark Oak Trapdoor", 3, "Dark Oak Planks", 6],
  ["Spruce Trapdoor", 3, "Spruce Planks", 6],
  ["Mangrove Trapdoor", 3, "Mangrove Planks", 6],
  ["Jungle Trapdoor", 3, "Jungle Planks", 6],
  ["Bamboo Trapdoor", 3, "Bamboo Planks", 6],
  ["Crimson Trapdoor", 3, "Crimson Planks", 6],
  ["Warped Trapdoor", 3, "Warped Planks", 6],
  ["Iron Trapdoor", 1, "Iron Ingots", 4],
  //Stairs
  ["Acacia Stairs", 4, "Acacia Planks", 6],
  ["Birch Stairs", 4, "Birch Planks", 6],
  ["Cherry Stairs", 4, "Cherry Planks", 6],
  ["Oak Stairs", 4, "Oak Planks", 6],
  ["Dark Oak Stairs", 4, "Dark Oak Planks", 6],
  ["Spruce Stairs", 4, "Spruce Planks", 6],
  ["Mangrove Stairs", 4, "Mangrove Planks", 6],
  ["Jungle Stairs", 4, "Jungle Planks", 6],
  ["Bamboo Stairs", 4, "Bamboo Planks", 6],
  ["Bamboo Mosaic Stairs", 4, "Bamboo Mosaic", 6],
  ["Crimson Stairs", 4, "Crimson Planks", 6],
  ["Warped Stairs", 4, "Warped Planks", 6],
  ["Andesite Stairs", 4, "Andesite", 6],
  ["Cobblestone Stairs", 4, "Cobblestone", 6],
  ["Blackstone Stairs", 4, "Blackstone", 6],
  ["Brick Stairs", 4, "Bricks", 6],
  ["Cobbled Deepslate Stairs", 4, "Cobbled Deepslate", 6],
  ["Cut Copper Stairs", 4, "Cut Copper", 6],
  ["Dark Prismarine Stairs", 4, "Dark Prismarine", 6],
  ["Diorite Stairs", 4, "Diorite", 6],
  ["Deepslate Brick Stairs", 4, "Deepslate Brick", 6],
  ["Deepslate Tile Stairs", 4, "Deepslate Tile", 6],
  ["End Stone Brick Stairs", 4, "End Stone Brick", 6],
  ["Exposed Cut Copper Stairs", 4, "Exposed Cut Copper", 6],
  ["Mossy Cobblestone Stairs", 4, "Mossy Cobblestone", 6],
  ["Mossy Stone Brick Stairs", 4, "Mossy Stone Brick", 6],
  ["Mud Brick Stairs", 4, "Mud Brick", 6],
  ["Nether Brick Stairs", 4, "Nether Brick", 6],
  ["Oxidized Cut Copper Stairs", 4, "Oxidized Cut Copper", 6],
  ["Polished Andesite Stairs", 4, "Polished Andesite", 6],
  ["Polished Blackstone Stairs", 4, "Polished Blackstone", 6],
  ["Polished Blackstone Brick Stairs", 4, "Polished Blackstone Brick", 6],
  ["Polished Deepslate Stairs", 4, "Polished Deepslate", 6],
  ["Polished Diorite Stairs", 4, "Polished Deepslate", 6],
  ["Prismarine Brick Stairs", 4, "Prismarine Brick", 6],
  ["Purpur Stairs", 4, "Purpur Brick", 6],
  ["Quartz Stairs", 4, "Quartz", 6],
  ["Red Nether Brick Stairs", 4, "Red Nether Brick", 6],
  ["Red Sandstone Stairs", 4, "Red Sandstone", 6],
  ["Sandstone Stairs", 4, "Sandstone", 6],
  ["Smooth Quartz Stairs", 4, "Smooth Quartz", 6],
  ["Smooth Red Sandstone Stairs", 4, "Smooth Red Sandstone", 6],
  ["Smooth Sandstone Stairs", 4, "Smooth Sandstone", 6],
  ["Stone Brick Stairs", 4, "Stone Brick", 6],
  ["Stone Stairs", 4, "Stone", 6],
  ["Waxed Cut Copper Stairs", 4, "Waxed Cut Copper", 6],
  ["Waxed Oxidized Cut Copper Stairs", 4, "Waxed Oxidized Cut Copper", 6],
  ["Waxed Weathered Cut Copper Stairs", 4, "Waxed Weathered Cut Copper", 6],
  ["Weathered Cut Copper Stairs", 4, "Weathered Cut Copper", 6],
  //Buttons
  ["Acacia Button", 1, "Acacia Planks", 1],
  ["Birch Button", 1, "Birch Planks", 1],
  ["Cherry Button", 1, "Cherry Planks", 1],
  ["Oak Button", 1, "Oak Planks", 1],
  ["Dark Oak Button", 1, "Dark Oak Planks", 1],
  ["Spruce Button", 1, "Spruce Planks", 1],
  ["Mangrove Button", 1, "Mangrove Planks", 1],
  ["Jungle Button", 1, "Jungle Planks", 1],
  ["Bamboo Button", 1, "Bamboo Planks", 1],
  ["Crimson Button", 1, "Crimson Planks", 1],
  ["Warped Button", 1, "Warped Planks", 1],
  //Pressure Plates
    ["Acacia Pressure Plate", 1, "Acacia Planks", 2],
    ["Birch Pressure Plate", 1, "Birch Planks", 2],
    ["Cherry Pressure Plate", 1, "Cherry Planks", 2],
    ["Oak Pressure Plate", 1, "Oak Planks", 2],
    ["Dark Oak Pressure Plate", 1, "Dark Oak Planks", 2],
    ["Spruce Pressure Plate", 1, "Spruce Planks", 2],
    ["Mangrove Pressure Plate", 1, "Mangrove Planks", 2],
    ["Jungle Pressure Plate", 1, "Jungle Planks", 2],
    ["Bamboo Pressure Plate", 1, "Bamboo Planks", 2],
    ["Crimson Pressure Plate", 1, "Crimson Planks", 2],
    ["Warped Pressure Plate", 1, "Warped Planks", 2],
  //Walls
  ["Andesite Wall", 6, "Andesite", 6],
  ["Cobblestone Wall", 6, "Cobblestone", 6],
  ["Blackstone Wall", 6, "Blackstone", 6],
  ["Cobbled Deepslate Wall", 6, "Cobbled Deepslate", 6],
  ["Deepslate Brick Wall", 6, "Deepslate Brick", 6],
  ["Deepslate Tile Wall", 6, "Deepslate Tile", 6],
  ["Diorite Wall", 6, "Diorite", 6],
  ["Mossy Cobblestone Wall", 6, "Mossy Cobblestone", 6],
  ["Mossy Stone Brick Wall", 6, "Mossy Stone Brick", 6],
  ["Mud Brick Wall", 6, "Mud Brick", 6],
  ["Nether Brick Wall", 6, "Nether Brick", 6],
  ["Polished Blackstone Brick Wall", 6, "Polished Blackstone Brick", 6],
  ["Polished Blackstone Wall", 6, "Polished Blackstone", 6],
  ["Polished Deepslate Wall", 6, "Polished Deepslate ", 6],
  ["Prismarine Wall", 6, "Prismarine", 6],
  ["Sandstone Wall", 6, "Sandstone", 6],
  ["Red Sandstone Wall", 6, "Red Sandstone", 6],
  ["Red Nether Brick Wall", 6, "Red Nether Brick", 6],
  ["Stone Brick Wall", 6, "Stone Brick", 6],
  //Gates
  ["Acacia Gate", 1, "Acacia Planks", 2, "Sticks", 4],
  ["Birch Gate", 1, "Birch Planks", 2, "Sticks", 4],
  ["Cherry Gate", 1, "Cherry Planks", 2, "Sticks", 4],
  ["Oak Gate", 1, "Oak Planks", 2, "Sticks", 4],
  ["Dark Oak Gate", 1, "Oak Planks", 2, "Sticks", 4],
  ["Spruce Gate", 1, "Spruce Planks", 2, "Sticks", 4],
  ["Jungle Gate", 1, "Jungle Planks", 2, "Sticks", 4],
  ["Mangrove Gate", 1, "Mangrove Planks", 2, "Sticks", 4],
  ["Bamboo Gate", 1, "Bamboo Planks", 2, "Sticks", 4],
  ["Crimson Gate", 1, "Crimson Planks", 2, "Sticks", 4],
  ["Warped Gate", 1, "Warped Planks", 2, "Sticks", 4],
  //Fences
  ["Acacia Fence", 3, "Acacia Planks", 4, "Sticks", 2],
  ["Birch Fence", 3, "Birch Planks", 4, "Sticks", 2],
  ["Oak Fence", 3, "Oak Planks", 4, "Sticks", 2],
  ["Cherry Fence", 3, "Oak Planks", 4, "Sticks", 2],
  ["Dark Oak Fence", 3, "Dark Oak Planks", 4, "Sticks", 2],
  ["Spruce Fence", 3, "Spruce Planks", 4, "Sticks", 2],
  ["Jungle Fence", 3, "Jungle Planks", 4, "Sticks", 2],
  ["Mangrove Fence", 3, "Mangrove Planks", 4, "Sticks", 2],
  ["Crimson Fence", 3, "Crimson Planks", 4, "Sticks", 2],
  ["Warped Fence", 3, "Warped Planks", 4, "Sticks", 2],
  ["Bamboo Fence", 3, "Bamboo Planks", 4, "Sticks", 2],
  //hanging signs
  ["Acacia Hanging Sign", 6, "Iron Chains", 2, "Stripped Acacia Logs", 6],
  ["Birch Hanging Sign", 6, "Iron Chains", 2, "Stripped Birch Logs", 6],
  ["Oak Hanging Sign", 6, "Iron Chains", 2, "Stripped Oak Logs", 6],
  ["Cherry Hanging Sign", 6, "Iron Chains", 2, "Stripped Cherry Logs", 6],
  ["Dark Oak Hanging Sign", 6, "Iron Chains", 2, "Stripped Dark Oak Logs", 6],
  ["Spruce Hanging Sign", 6, "Iron Chains", 2, "Stripped Spruce Logs", 6],
  ["Jungle Hanging Sign", 6, "Iron Chains", 2, "Stripped Jungle Logs", 6],
  ["Mangrove Hanging Sign", 6, "Iron Chains", 2, "Stripped Mangrove Logs", 6],
  ["Crimson Hanging Sign", 6, "Iron Chains", 2, "Stripped Crimson Logs", 6],
  ["Warped Hanging Sign", 6, "Iron Chains", 2, "Stripped Warped Logs", 6],
  ["Bamboo Hanging Sign", 6, "Iron Chains", 2, "Stripped Bamboo", 6],
  //Add other fences and signs
  ["Birch Sign", 3, "Birch Planks", 6, "Sticks", 1],
  ["Acacia Sign", 3, "Acacia Planks", 6, "Sticks", 1],
  ["Oak Sign", 3, "Oak Planks", 6, "Sticks", 1],
  ["Dark Oak Sign", 3, "Dark Oak Planks", 6, "Sticks", 1],
  ["Jungle Sign", 3, "Jungle Planks", 6, "Sticks", 1],
  ["Spruce Sign", 3, "Jungle Planks", 6, "Sticks", 1],
  ["Cherry Sign", 3, "Cherry Planks", 6, "Sticks", 1],
  ["Mangrove Sign", 3, "Mangrove Planks", 6, "Sticks", 1],
  ["Bamboo Sign", 3, "Bamboo Planks", 6, "Sticks", 1],
  ["Crimson Sign", 3, "Crimson Planks", 6, "Sticks", 1],
  ["Warped Sign", 3, "Warped Planks", 6, "Sticks", 1],
  //Redstone Items
  ["Observer", 1, "Cobblestone", 6, "Redstone Dust", 2, "Nether Quartz", 1],
  ["Lever", 1, "Stick", 1, "Cobblestone", 1],
  ["Redstone Torch", 1, "Redstone Dust", 1, "Sticks", 1],
  [ "Piston", 1, "Cobblestone", 4, "Iron Ingot", 1, "Redstone Dust", 1, "Planks", 3],
  ["Sticky Piston", 1, "Slime Ball", 1, "Piston", 1],
  ["Repeater", 1, "Stone", 6, "Redstone Dust", 1, "Redstone Torch", 2],
  ["Dispenser", 1, "Cobblestone", 7, "Bow", 1, "Redstone Dust", 1],
  ["Jukebox", 1, "Planks", 8, "Diamonds", 1],
  ["Minecart", 1, "Iron Ingots", 5],
  ["Chest Minecart", 1, "Chest", 1, "Minecart", 1],
  ["Chest Minecart", 1, "Chest", 1, "Minecart", 1],
  ["Rail", 16, "Iron Ingots", 6, "Stick", 1],
  ["Powered Rail", 6, "Gold Ingots", 6, "Stick", 1, "Redstone Dust", 1],
  ["Detector Rail", 6, "Iron Ingots", 6, "Stone Slab", 1, "Redstone Dust", 1],
  ["Activator Rail", 6, "Iron Ingots", 6, "Sticks", 2, "Redstone Torch", 1],
  ["Redstone Lamp", 1, "Redstone Dust", 4, "Glowstone", 1],
  ["Tripwire Hook", 1, "Planks", 1, "Iron Ingot", 1, "Stick", 1],
  ["Daylight Detector", 1, "Glass", 3, "Nether Quartz", 3, "Slabs", 3],
  ["Dropper", 1, "Cobblestone", 7, "Redstone Dust", 1],
  ["Hopper", 1, "Iron Ingots", 5, "Chest", 1],
  ["Hopper Minecart", 1, "Hopper", 1, "Minecart", 1],
  ["Furnace Minecart", 1, "Furnace", 1, "Minecart", 1],
  ["TNT", 1, "Sand", 4, "Gunpowder", 5],
  ["TNT Minecart", 1, "Minecart", 1, "TNT", 1],
  ["Comparator", 1, "Cobblestone", 3, "Redstone Torch", 3, "Nether Quartz", 1],
  ["Trapped Chest", 1, "Chest", 1, "Tripwire Hook", 1],
  ["Target", 1, "Hay Bale", 1, "Redstone Dust", 4],
  ["Calibrated Sculk Sensor", 1, "Amethyst Shard", 3, "Sculk Sensor", 1],

  //Food Items
  ["Hay Block", 1, "Wheat", 9],
  ["Cake", 1, "Wheat", 3, "Milk Bucket", 3, "Sugar", 2, "Eggs", 1],
  ["Bread", 1, "Wheat", 3],
  ["Cookie", 1, "Wheat", 2, "Cocoa Beans", 1],
  ["Bowl", 1, "Planks", 3],
  ["Mushroom Stew", 1, "Bowl", 1, "Brown Mushroom", 1, "Red Mushroom", 1],
  ["Golden Apple", 1, "Apple", 1, "Gold Ingots", 8],
  ["Golden Carrot", 1, "Carrot", 1, "Gold Nuggets", 8],
  ["Pumpkin Pie", 1, "Pumpkin", 1, "Sugar", 1, "Egg", 1],

  //Tools
  ["Wooden Axe", 1, "Planks", 3, "Sticks", 2],
  ["Wooden Sword", 1, "Planks", 2, "Sticks", 1],
  ["Wooden Pickaxe", 1, "Planks", 3, "Sticks", 2],
  ["Wooden Shovel", 1, "Planks", 1, "Sticks", 2],
  ["Wooden Hoe", 1, "Planks", 2, "Sticks", 2],
  ["Stone Axe", 1, "Cobblestone", 3, "Sticks", 2],
  ["Stone Sword", 1, "Cobblestone", 2, "Sticks", 1],
  ["Stone Pickaxe", 1, "Cobblestone", 3, "Sticks", 2],
  ["Stone Shovel", 1, "Cobblestone", 1, "Sticks", 2],
  ["Stone Hoe", 1, "Cobblestone", 2, "Sticks", 2],
  ["Iron Axe", 1, "Iron Ingots", 3, "Sticks", 2],
  ["Iron Sword", 1, "Iron Ingots", 2, "Sticks", 1],
  ["Iron Pickaxe", 1, "Iron Ingots", 3, "Sticks", 2],
  ["Iron Shovel", 1, "Iron Ingots", 1, "Sticks", 2],
  ["Iron Hoe", 1, "Gold Ingots", 2, "Sticks", 2],
  ["Golden Axe", 1, "Gold Ingots", 3, "Sticks", 2],
  ["Golden Sword", 1, "Gold Ingots", 2, "Sticks", 1],
  ["Golden Pickaxe", 1, "Gold Ingots", 3, "Sticks", 2],
  ["Golden Shovel", 1, "Gold Ingots", 1, "Sticks", 2],
  ["Golden Hoe", 1, "Gold Ingots", 2, "Sticks", 2],
  ["Diamond Axe", 1, "Diamonds", 3, "Sticks", 2],
  ["Diamond Sword", 1, "Diamonds", 2, "Sticks", 1],
  ["Diamond Pickaxe", 1, "Diamonds", 3, "Sticks", 2],
  ["Diamond Shovel", 1, "Diamonds", 1, "Sticks", 2],
  ["Diamond Hoe", 1, "Diamonds", 2, "Sticks", 2],
  ["Netherite Axe", 1, "Netherite Ingots", 3, "Sticks", 2],
  ["Netherite Sword", 1, "Netherite Ingots", 2, "Sticks", 1],
  ["Netherite Pickaxe", 1, "Netherite Ingots", 3, "Sticks", 2],
  ["Netherite Shovel", 1, "Netherite Ingots", 1, "Sticks", 2],
  ["Netherite Hoe", 1, "Netherite Ingots", 2, "Sticks", 2],
  ["Bow", 1, "String", 3, "Sticks", 3],
  ["Shield", 1, "Planks", 6, "Iron Ingots", 1],
  // ["Horse Armor", 1, "Leather", 7],
  ["Arrow", 4, "Flint", 1, "Sticks", 1, "Feather", 1],
  ["Spectral Arrow", 2, "Arrow", 1, "Glowstone Dust", 4],
  ["Tipped Arrow", 8, "Arrow", 8, "Glowstone Dust", 4],
  ["Torch", 4, "Coal", 1, "Sticks", 1],
  ["Chest", 1, "Planks", 8],
  ["Acacia Boat", 1, "Acacia Planks", 5],
  ["Birch Boat", 1, "Birch Planks", 5],
  ["Spruce Boat", 1, "Spruce Planks", 5],
  ["Oak Boat", 1, "Oak Planks", 5],
  ["Dark Oak Boat", 1, "Dark Oak Planks", 5],
  ["Cherry Boat", 1, "Cherry Planks", 5],
  ["Jungle Boat", 1, "Jungle Planks", 5],
  ["Mangrove Boat", 1, "Mangrove Planks", 5],
  ["Bamboo Raft", 1, "Bamboo Planks", 5],
  ["Stick", 4, "Planks", 2],
  ["Crafting Table", 1, "Planks", 4],
  ["Boat with Chest", 1, "Chest", 1, "Boat", 1],
  ["Furnace", 1, "Cobblestone", 8],
  ["Ladder", 3, "Sticks", 7],
  ["Fishing Rod", 1, "Sticks", 3, "String", 2],
  ["Flint and Steel", 1, "Flint", 1, "Steel", 1],
  ["Shears", 1, "Iron Ingot", 2],
  ["Bucket", 1, "Iron Ingot", 3],
  ["Clock", 1, "Gold Ingot", 4, "Redstone Dust", 1],
  ["Compass", 1, "Iron Ingot", 4, "Redstone Dust", 1],
  ["Map", 1, "Paper", 8, "Compass", 1],
  ["Shulker Box", 1, "Chest", 1, "Shulker", 2],
  ["Spyglass", 1, "Echo Shard", 8, "Compass", 1],
  ["Brush", 1, "Feather", 1, "Copper Ingot", 1, "Sticks", 1],
  ["Conduit", 1, "Nautilus Shell", 8, "Heart of the Sea", 1],
  ["Turtle Helmet", 1, "Scute", 5],
  ["Crossbow", 1, "String", 2, "Iron Ingot", 1, "Tripwire Hook", 1, "Sticks", 3],
  //Armour
  ["Leather Helmet", 1, "Leather", 5],
  ["Leather Boots", 1, "Leather", 4],
  ["Leather Chestplate", 1, "Leather", 8],
  ["Leather Leggings", 1, "Leather", 7],
  ["Iron Helmet", 1, "Iron Ingots", 5],
  ["Iron Boots", 1, "Iron Ingots", 4],
  ["Iron Chestplate", 1, "Iron Ingots", 8],
  ["Iron Leggings", 1, "Iron Ingots", 7],
  ["Golden Helmet", 1, "Gold Ingots", 5],
  ["Golden Boots", 1, "Gold Ingots", 4],
  ["Golden Chestplate", 1, "Gold Ingots", 8],
  ["Golden Leggings", 1, "Gold Ingots", 7],
  ["Diamond Helmet", 1, "Diamonds", 5],
  ["Diamond Boots", 1, "Diamonds", 4],
  ["Diamond Chestplate", 1, "Diamonds", 8],
  ["Diamond Leggings", 1, "Diamonds", 7],
  ["Netherite Helmet", 1, "Diamond Helmet", 1, "Netherite Ingot", 1, "Smithing Template", 1],
  ["Netherite Boots", 1,  "Diamond Boots", 1, "Netherite Ingot", 1, "Smithing Template", 1],
  ["Netherite Chestplate", 1,  "Diamond Chestplate", 1, "Netherite Ingot", 1, "Smithing Template", 1],
  ["Netherite Leggings", 1,  "Diamond Leggings", 1, "Netherite Ingot", 1, "Smithing Template", 1],
  ["Leather Horse Armor", 1, "Leather", 7],

  //Other Blocks - Decorative and Building Blocks
  ["Glowstone", 1, "Glowstone Dust", 4],
  ["Snow Block", 1, "Snowballs", 4],
  ["Stone Bricks", 4, "Stone", 4],
  ["Bricks", 1, "Brick", 4],
  ["Sandstone", 1, "Sand", 4],
  ["Smooth Sandstone", 4, "Sandstone", 4],
  ["Gold Block", 1, "Gold Ingots", 9],
  ["Iron Block", 1, "Iron Ingots", 9],
  ["Diamond Block", 1, "Diamonds", 9],
  ["Lapis Block", 1, "Lapis Lazuli", 9],
  ["Redstone Block", 1, "Redstone Dust", 9],
  ["Emerald Block", 1, "Emeralds", 9],
  ["Coal Block", 1, "Coal", 9],
  ["Note Block", 1, "Planks", 8, "Redstone Dust", 1],
  ["Clay", 1, "Clay Ball", 4],
  ["Jack-o-Lantern", 1, "Pumpkin", 1, "Torch", 1],
  ["Nether Bricks", 1, "Nether Bricks", 4],
  ["Red Nether Bricks", 1, "Nether Bricks", 2, "Nether Wart", 2],
  ["Chiseled Nether Bricks", 1, "Nether Brick Slabs", 2],
  ["Nether Wart Block", 1, "Nether Wart ", 9],
  ["Quartz Block", 1, "Quartz", 4],
  ["Chiseled Quartz Block", 1, "Quartz Slabs", 2],
  ["Quartz Pillar", 1, "Quartz Block", 2],
  ["Quartz Bricks", 1, "Quartz Block", 4],
  //Polished Rocks
  ["Polished Granite", 1, "Granite", 4],
  ["Polished Andesite", 1, "Andesite", 4],
  ["Polished Diorite", 1, "Diorite", 4],
  ["Polished Basalt", 1, "Basalt", 4],
  ["Polished Blackstone", 1, "Blackstone", 4],
  ["Chiseled Polished Blackstone", 1, "Polished Blackstone Slabs", 2],
  ["Polished Blackstone Bricks", 1, "Polished Blackstone", 4],
  ["Slime Block", 1, "Slime Balls", 9],
  ["Mossy Stone Bricks", 1, "Stone Bricks", 1, "Moss Block", 1],
  ["Chiseled Stone Bricks", 1, "Stone Brick Slabs", 2],
  ["Smooth Red Sandstone", 1, "Red Sandstone", 4],
  ["Chiseled Sandstone", 1, "Sandstone Slabs", 2],
  ["Chiseled Red Sandstone", 1, "Red Sandstone Slabs", 2],
  ["Purpur Block", 1, "Purpur", 4],
  ["Purpur Pillar", 1, "Purpur Slabs", 2],
  ["Magma Block", 1, "Magma Cream", 4],
  ["Bone Block", 1, "Bone Meal", 9],
  ["Dried Kelp Block", 1, "Dried Kelp", 9],
  ["Packed Ice", 1, "Ice", 9],
  ["Blue Ice", 1, "Packed Ice", 9],
  ["Honey Block", 1, "Honey Bottles", 4],
  ["Honeycomb Block", 1, "Honeycomb", 4],
  ["Bamboo Block", 1, "Bamboo", 9],
  ["Netherite Block", 1, "Netherite Ingots", 9],
  ["Amethyst Block", 1, "Amethyst Shards", 4],
  ["Copper Block", 1, "Copper Ingots", 9],
  ["Cut Copper", 1, "Copper Blocks", 4],
  ["Waxed Copper Block", 1, "Copper Block", 1, "Honeycomb", 1],
  ["Dripstone Block", 1, "Dripstone", 4],
  ["Muddy Mangrove Roots", 1, "Mangrove Roots", 1, "Mud", 1],
  ["Packed Mud", 1, "Wheat", 1, "Mud", 1],
  ["Mud Bricks", 4, "Mud", 4],
  ["Bamboo Mosaic", 1, "Bamboo Slabs", 2],
  ["Chiseled Bookshelf", 1, "Planks", 6, "Slabs", 3],
  //Wood
  ["Spruce Wood", 3, "Spruce Logs", 4],
["Oak Wood", 3, "Oak Logs", 4],
["Dark Oak Wood", 3, "Dark Oak Logs", 4],
["Cherry Wood", 3 , "Cherry Logs", 4],
["Birch Wood", 3, "Birch Logs", 4],
["Acacia Wood", 3, "Acacia Logs", 4],
["Mangrove Wood", 3, "Mangrove Logs", 4],
["Jungle Wood", 3, "Jungle Logs", 4],
["Crimson Hyphae", 3, "Crimson Stem", 4],
["Warped Hyphae", 3, "Warped Stem", 4],

//Stripped Wood
["Stripped Spruce Wood", 3, "Stripped Spruce Logs", 4],
["Stripped Oak Wood", 3, "Stripped Oak Logs", 4],
["Stripped Dark Oak Wood", 3, "Stripped Dark Oak Logs", 4],
["Stripped Cherry Wood", 3 , "Stripped Cherry Logs", 4],
["Stripped Birch Wood", 3, "Stripped Birch Logs", 4],
["Stripped Acacia Wood", 3, "Stripped Acacia Logs", 4],
["Stripped Mangrove Wood", 3, "Stripped Mangrove Logs", 4],
["Stripped Jungle Wood", 3, "Stripped Jungle Logs", 4],
["Stripped Crimson Hyphae", 3, "Stripped Crimson Stems", 4],
["Stripped Warped Hyphae", 3, "Stripped Warped Stems", 4],



  //Terracotta
  ["Blue Terracotta", 8, "Blue Dye", 1, "Terracotta", 8],
  ["Light Blue Terracotta", 8, "Light Blue Dye", 1, "Terracotta", 8],
  ["Purple Terracotta", 8, "Purple Dye", 1, "Terracotta", 8],
  ["Cyan Terracotta", 8, "Cyan Dye", 1, "Terracotta", 8],
  ["Pink Terracotta", 8, "Pink Dye", 1, "Terracotta", 8],
  ["Yellow Terracotta", 8, "Yellow Dye", 1, "Terracotta", 8],
  ["Green Terracotta", 8, "Green Dye", 1, "Terracotta", 8],
  ["Lime Terracotta", 8, "Lime Dye", 1, "Terracotta", 8],
  ["Red Terracotta", 8, "Red Dye", 1, "Terracotta", 8],
  ["Orange Terracotta", 8, "Orange Dye", 1, "Terracotta", 8],
  ["Magenta Terracotta", 8, "Magenta Dye", 1, "Terracotta", 8],
  ["Gray Terracotta", 8, "Gray Dye", 1, "Terracotta", 8],
  ["Light Gray Terracotta", 8, "Light Gray Dye", 1, "Terracotta", 8],
  ["Brown Terracotta", 8, "Brown Dye", 1, "Terracotta", 8],
  ["Black Terracotta", 8, "Black Dye", 1, "Terracotta", 8],




  //Dyes
  ["Blue Dye", 1, "Lapis Lazuli or Cornflower", 1],
  ["Light Blue Dye", 1, "Blue Dye", 1, "White Dye", 1],
  ["Purple Dye", 1, "Blue Dye", 1, "Red Dye", 1],
  ["Cyan Dye", 1, "Blue Dye", 1, "Green Dye", 1],
  ["Pink Dye", 1, "White Dye", 1, "Red Dye", 1],
  ["Yellow Dye", 1, "Dandelion or Sunflower", 1],
  ["Green Dye", 1, "Cactus", 1],
  ["Lime Dye", 1, "Green Dye", 1, "White Dye", 1],
  ["Red Dye", 1, "Poppy", 1],
  ["Orange Dye", 1, "Yellow Dye", 1, "Red Dye", 1],
  ["Magenta Dye", 1, "Purple Dye", 1, "Pink Dye", 1],
  ["Gray Dye", 1, "White Dye", 1, "Black Dye", 1],
  ["Light Gray Dye", 1, "Gray Dye", 1, "White Dye", 1],
  ["Brown Dye", 1, "Cocoa Beans", 1],
  ["Black Dye", 1, "Ink Sac", 1],
  ["White Dye", 1, "Bone Meal", 1],
  //Brewing
  ["Glass Bottle", 3, "Glass", 3],
  ["Cauldron", 1, "Iron Ingots", 7],
  ["Brewing Stand", 1, "Cobblestone", 3, "Blaze Rod", 1],
  ["Blaze Powder", 1, "Blaze Rods", 1],
  ["Fermented Spider Eye", 1, "Spider Eye", 1, "Sugar", 1, "Brown Mushroom", 1],
  ["Glistering Melon Slice", 1, "Melon Slice", 1, "Gold Nuggets", 8],
  //Wool
  ["Blue Wool", 1, "Blue Dye", 1, "White Wool", 1],
  ["Light Blue Wool", 1, "Light Blue Dye", 1, "White Wool", 1],
  ["Purple Wool", 1, "Purple Dye", 1, "White Wool", 1],
  ["Cyan Wool", 1, "Cyan Dye", 1, "White Wool", 1],
  ["Pink Wool", 1, "Pink Dye", 1, "White Wool", 1],
  ["Yellow Wool", 1, "Yellow Dye", 1, "White Wool", 1],
  ["Green Wool", 1, "Green Dye", 1, "White Wool", 1],
  ["Lime Wool", 1, "Lime Dye", 1, "White Wool", 1],
  ["Red Wool", 1, "Red Dye", 1, "White Wool", 1],
  ["Orange Wool", 1, "Orange Dye", 1, "White Wool", 1],
  ["Magenta Wool", 1, "Magenta Dye", 1, "White Wool", 1],
  ["Gray Wool", 1, "Gray Dye", 1, "White Wool", 1],
  ["Light Gray Wool", 1, "Light Gray Dye", 1, "White Wool", 1],
  ["Brown Wool", 1, "Brown Dye", 1, "White Wool", 1],
  ["Black Wool", 1, "Black Dye", 1, "White Wool", 1],
  //Carpet
  ["Blue Carpet", 3, "Blue White Wool", 2],
  ["Light Blue Carpet", 3, "Light Blue Wool", 2],
  ["Purple Carpet", 3, "Purple Dye Wool", 2],
  ["Cyan Carpet", 3, "Cyan Dye Wool", 2],
  ["Pink Carpet", 3, "Pink Dye Wool", 2],
  ["Yellow Carpet", 3, "Yellow Wool", 2],
  ["Green Carpet", 3, "Green Wool", 2],
  ["Lime Carpet", 3, "Lime Wool", 2],
  ["Red Carpet", 3, "Red Wool", 2],
  ["Orange Carpet", 3, "Orange Wool", 2],
  ["Magenta Carpet", 3, "Magenta Wool", 2],
  ["Gray Carpet", 3, "Gray Wool", 2],
  ["Light Gray Carpet", 3, "Light Gray Wool", 2],
  ["Brown Carpet", 3, "Brown Wool", 2],
  ["Black Carpet", 3, "Black Wool", 2],
  ["Moss Carpet", 3, "Moss Carpet", 2],
  //Misc
  ["Fire Charge", 3, "Blaze Powder", 1, "Coal", 1, "Gunpowder", 1],
  ["Beacon", 1, "Glass", 5, "Obsidian", 3, "Nether Star", 1],
  ["Flower Pot", 1, "Brick", 3],
  ["Carrot on a Stick", 1, "Fishing Rod", 1, "Carrot", 1],
  ["Warped Fungus on a Stick", 1, "Fishing Rod", 1, "Warped Fungus", 1],
  ["Firework Rocket", 1, "Paper", 1, "Gunpowder", 3],
  ["End Rod", 4, "Blaze Rod", 1, "Popped Chorus Fruit", 1],
  ["End Crystal", 1, "Glass", 7, "Ghast Tear", 1, "Eye of Ender", 1],
  ["Blue Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Blue Dye", 1],
  ["Light Blue Concrete Powder", 1,"Sand",4, "Gravel", 4, "Light Blue Dye", 1],
  ["Cyan Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Cyan Dye", 1],
  ["Red Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Red Dye", 1],
  ["Pink Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Pink Dye", 1],
  ["Magenta Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Magenta Dye", 1],
  ["Purple Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Purple Dye", 1],
  ["Yellow Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Yellow Dye", 1],
  ["Orange Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Orange Dye", 1],
  ["Green Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Green Dye", 1],
  ["Lime Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Lime Dye", 1],
  ["Purple Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Purple Dye", 1],
  ["Black Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Black Dye", 1],
  ["Brown Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Brown Dye", 1],
  ["Gray Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Gray Dye", 1],
  ["Light Gray Concrete Powder", 1, "Sand", 4, "Gravel", 4, "Light Gray Dye", 1],
  ["Netherite Ingot", 1, "Gold Ingot", 4, "Netherite Scrap", 4],
  ["Respawn Anchor", 1, "Crying Obsidian", 6, "Glowstone", 3],
  ["Lodestone", 1, "Chiseled Stone Bricks", 8, "Netherite Ingots", 1],
  ["Candle", 1, "Honeycomb", 1, "String", 1],
  ["Lightning Rod", 1, "Copper Ingots", 3],
  ["Tinted Glass", 2, "Amethyst Shard", 4, "Glass", 1],
  ["Decorated Pot", 1, "Brick", 4],
];
